### ISSUE TITLE
Game Rooms Bug

### ISSUE THREAD

**Issue by stewartanderson3** [stewie1570/tetris#341]
Room is deleted when player connects to host.

```console
{System.NotImplementedException: RedisHubLifetimeManager`1 does not support client return values.
   at Microsoft.AspNetCore.SignalR.HubLifetimeManager`1.InvokeConnectionAsync[T](String connectionId, String methodName, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Internal.HubCallerClients.SingleClientProxy.InvokeCoreAsync[T](String method, Object[] args, CancellationToken cancellationToken)
   at Tetris.Hubs.GameHub.Hello(GroupMessage helloMessage) in C:\Users\stander\tetris\Tetris\Hubs\GameHub.cs:line 77}
```

**Comment by stewartanderson3** [comment]
Fixed
